version: '3'
services:
  gin:
    build:
      context: ./docker/go
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
    volumes:
      - ./src:/go/src
    ports:
      - 8888:8080
    networks:
      - gin-practice
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - 3336:3306
    networks:
      - gin-practice
networks:
    gin-practice:
        external: true
